name: Empson
favicon: null
layout_spectrum: 0.8054918865673244
typography_spectrum: 0.7117939575109631
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.7996672133449465
  lightness: 0.5
  saturation: 0.9857264410238713
  rhythmicContrast: 0.0881376788020134
purpose: []
